title: Albert Choi Portfolio
description: Albert Choi's Portfolio website. Here are some of my skills and experiences put into resume form
  <br><br>
  <a href="/about">About</a>
  <br><br> 
  <a href="/Portfolio">Portfolio</a>
  <br><br>
  <a href="/subscribe">Subscribe</a>
  <br><br>
  <a href="/privacy_policy">Privacy Policy</a>
  
theme: jekyll-theme-minimal
google_analytics: G-LG6PBB02Q5 # your Google Analytics tracking ID here
